### ISSUE TITLE
Figure out teams structure for organisation

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/procedures-and-practices#9]
We need teams for various functions, including code review, offsite CI run approval and CI deployment approval for policies (#8).

As a team member this makes it simpler to know who to assign for review (a team rather than an individual).

Assigning teams to reviews shares the burden of reviewing.

As a team leader this enables flexibility to add and remove team members from teams, for workload reasons, or reorganisation.

As a senior executive of the organisation approvals for policies provides a mechanism for approval that provides an audit trail and integrates seamlessly with the ZenHub/GitHub workflows.

**Comment by aidanheerdegen** [comment]
@AndyHoggANU @rbeucher @ccarouge @MartinDix @kdruken

Sorry to ping everyone, but this is important. We need some discussion about how this works. I haven't pinged the others yet, but thought I would once we've got some idea how we want to set this up.

**Comment by aidanheerdegen** [comment]
Some background information:

About GitHub Teams

https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams

Approving workflow runs - this is how we can add an approval layer for policies being published to a website

https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments

GitHub permissions

https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization

**Comment by aidanheerdegen** [comment]
The teams will be defined at the organisation level. Permissions are then granted on a per-repo basis.

So for example, I imagine we will have teams for code review, but how to organise this? I think it makes sense to have review teams that are quite specialised, e.g. atmosphere, ocean, land, evaluation, and more general teams as well. I also envisage having a testing-infrastructure team for overseeing the secure testing.

I believe we can add in-kind collaborators and other collaborators to teams, though the specifics of the best way to do that is yet to be determined.

**Comment by ccarouge** [comment]
For the CABLE community repo, I think I could use a code review team and a science review team, to review the science evaluation tests. I may need non-NRI reviewers on the ACCESS-NRI's CABLE repo as well but those might be more ad-hoc.

**Comment by rbeucher** [comment]
Teams are quite flexible. We can create them / organise and delete them quite easily so I suggest we try and see.
There are some obvious ones for the NRI (our teams, OCEAN, LAND, ATMOSPHERE, TRAINING, MED, RELEASE). 
We need an EXECUTIVE team for the high level stuff.
I would leave the organisation of child teams to the leader of the respective teams...
For the community:
 Science reviews teams for each domain make sense. One general review team to check for good practice, format etc,.. 
I see there is a Contributors team... that one does not make sense to me. Anyone can contribute, we don't need a team for that.

**Comment by rbeucher** [comment]
Actually I'm not convinced by the idea of separating code/science/mode evaluation. We fall in the classic division of science vs code and I don't like that...We could use tags to clarify what is needed but I don't think we should separate science from technical stuff.

**Comment by aidanheerdegen** [comment]
> Teams are quite flexible. We can create them / organise and delete them quite easily so I suggest we try and see.
> There are some obvious ones for the NRI (our teams, OCEAN, LAND, ATMOSPHERE, TRAINING, MED, RELEASE).
> We need an EXECUTIVE team for the high level stuff.
> I would leave the organisation of child teams to the leader of the respective teams...

All these teams should be part of a larger Staff team. Do we make a distinction between in-kind and directly employed?

> For the community:
> Science reviews teams for each domain make sense. One general review team to check for good practice, format etc,..
> I see there is a Contributors team... that one does not make sense to me. Anyone can contribute, we don't need a team for that.

I set up some [teams in ACCESS-Hub](https://github.com/orgs/ACCESS-Hub/teams), one of which was Contributors, I guess that is what you're referring to?

That was the name I gave to people who have write access (approve PRs, push to a repo etc):

https://github.com/ACCESS-Hub/ACCESS-Hub/settings/access

so perhaps it was a poor choice of name, given that anyone can "contribute" by making a PR. So we should change the name. I had considered using "Editors", is that a better team name?

**Comment by rbeucher** [comment]
> > Teams are quite flexible. We can create them / organise and delete them quite easily so I suggest we try and see.
> > There are some obvious ones for the NRI (our teams, OCEAN, LAND, ATMOSPHERE, TRAINING, MED, RELEASE).
> > We need an EXECUTIVE team for the high level stuff.
> > I would leave the organisation of child teams to the leader of the respective teams...
> 
> All these teams should be part of a larger Staff team. Do we make a distinction between in-kind and directly employed?
> 
I think we should be clearly able to identify who is NRI... I would include the in-kinds...

> > For the community:
> > Science reviews teams for each domain make sense. One general review team to check for good practice, format etc,..
> > I see there is a Contributors team... that one does not make sense to me. Anyone can contribute, we don't need a team for that.
> 
> I set up some [teams in ACCESS-Hub](https://github.com/orgs/ACCESS-Hub/teams), one of which was Contributors, I guess that is what you're referring to?
> 
> That was the name I gave to people who have write access (approve PRs, push to a repo etc):
> 
> https://github.com/ACCESS-Hub/ACCESS-Hub/settings/access
> 
> so perhaps it was a poor choice of name, given that anyone can "contribute" by making a PR. So we should change the name. I had considered using "Editors", is that a better team name?

OK I see. Yes Editors is probably a better name

**Comment by aidanheerdegen** [comment]
So I've make a hierarchy of the existing teams on ACCESS-Hub to get a feel for how it works.

**Comment by aidanheerdegen** [comment]
Neat! There is some "load balancing" available for reviewing
![Screen Shot 2022-09-09 at 12 47 49 pm](https://user-images.githubusercontent.com/6063709/189261875-dc22d15b-307e-44ee-8d8c-6730c90c70b2.png)

**Comment by rbeucher** [comment]
OK so it's like an "Editorial team" for a journal with:
- Editor
- Assistant Editor
- Reviewers

**Comment by aidanheerdegen** [comment]
Ok, so something like this, where it is "Team Name: role" where role is optional and is either a [formal GitHub role](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization) or a role description
```mermaid
graph TD
A(Members: Read) --> B(Reviewers: Triage) --> C(Editors: Write)
C --> D
D(Staff) --> E(Maintainers: Maintain) --> F(Administrators: Admin)
G(Security: CI Admin)
H(Executive: Approvals)
D --> H
F --> G
I(Land)
J(Atmosphere)
K(Ocean)
L(MED)
M(Release)
N(Training)
B --> I
B --> J
B --> K
B --> L
B --> M
B --> N
```

**Comment by rbeucher** [comment]
Lets see if I understand. As MED Team Leader, I will be part of
- Reviewers
- MED
- Editors
- Staff
- Executive

Maintainers, Admin and Security for the MED repos?

That looks complicated...

**Comment by aidanheerdegen** [comment]
A few points:
- If we want granularity at team level (land, MED etc) you sort of can't get away with anything else. 
- We can split Staff out (and I did originally have it it's own hierarchy) but all that means is we have to add all Staff to two separate hierarchies. It would mean no fewer teams
- We can collapse some of the staff hierarchy and make everyone an Admin, but that goes against the principle of least privilege, and I can't be confident there isn't the possibility to do something inadvertently bad. Not everyone has the requisite knowledge to administer GitHub repos
- I don't think group leads will be in the Executive team. I see that being Director + ADs. There might be a layer in approvals.
- No-one is automatically on Security. That will be locked down to an absolute minimum.
- There is no reason Team Leads *have* to be Administrators, but certainly in the early set up phase it would be annoying not to be. Once it's all a bit more mature it might just be a burden to have people coming to you asking to do GitHub admin tasks.

**Comment by rbeucher** [comment]
OK. So Lets go for this and see if it works.
